### PR TITLE
3 decimal limit on profit

### PR DESCRIPTION
**Pull request by theskollie**
Fixed decimal limit on profit

Screenshot 2024-01-13 at 3 33 01 PM
Screenshot 2024-01-13 at 3 33 10 PM

### CODE REVIEW

**Comment by theskollie** [comment]
I was going to go with 2 decimal places but decided on 3 for those that want granular data but I don't think we need more than that lol

**Comment by REFLEXGAMING007** [comment]
I do think we need that for poor people like me.

Dont change it please bro

**Comment by REFLEXGAMING007** [comment]
I dca $0.10 minimum order with hundreds of coins in kucoin

**Comment by 3cqs-coder** [comment]
Profit rounding was actually already modified on the back-end in commit https://github.com/3cqs-coder/SymBot/commit/cda2e7677749878355503890e12bc294c326aacb to account for very minute trades, also referencing closed issue  https://github.com/3cqs-coder/SymBot/issues/15. This should probably remain this way unless there are thoughts on why it should be changed.

**Comment by REFLEXGAMING007** [comment]
Also it was before $0.1, I was the one who requested that change to that. so please don't change it

**Comment by REFLEXGAMING007** [comment]
My day already going shitty with crypto ban & tachiyomi copyright strike. Please don't make it any more worse 😓🙏

**Comment by theskollie** [comment]
> I do think we need that for poor people like me.
> 
> Dont change it please bro

This change is purely on the UI, and wouldn't effect the deal.
Makes sense tho, maybe I'll look to add it as toggle functionality. 
I think for 99% of the users, we don't want to know we are $0.0000034322 in profit

**Comment by REFLEXGAMING007** [comment]
Then make it a toggle in configaration settings so that we can choose it with a button if we want to show more decimals in profit section

**Comment by REFLEXGAMING007** [comment]
Also I'd love it see 0.00001 profit in all 300 rows

**Comment by theskollie** [comment]
Allowing for future taking profit in base, I don't think this will be worth implementing, even as toggle.
Might revisit in future, but will just run it locally for myself for now.

**Comment by theskollie** [comment]
Allowing for future taking profit in base, I don't think this will be worth implementing, even as toggle.
Might revisit in future, but will just run it locally for myself for now.

**Pull request closed without merging**
