### PR TITLE
Limit order fix

### PR DESCRIPTION
**Pull request by kenil-empiric**
Modified limit order functionality.

### CODE REVIEW

**Comment by REFLEXGAMING007** [comment]
Is this the feature that I suggested in symbot issue #21 


Sorry if I sound dumb here, I don't know how GitHub works tbh😅😓

**Comment by 3cqs-coder** [comment]
> Is this the feature that I suggested in symbot issue #21
> 
> Sorry if I sound dumb here, I don't know how GitHub works tbh😅😓

It is related since limit order features and functionality is in active development. :)

**Comment by REFLEXGAMING007** [comment]
Outstanding!! This is the only thing I'm waiting for to go in big time

**Comment by 3cqs-coder** [comment]
Closing PR as not relevant to current development

**Pull request closed without merging**
